apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: smart-ai-tutor
    component: frontend
spec:
  type: ClusterIP  # Internal service (exposed via Ingress)
  sessionAffinity: None

  selector:
    app: smart-ai-tutor
    component: frontend

  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
