#!/bin/bash

# Setup Secret Rotation for RDS Credentials
# This script configures automatic rotation for the RDS PostgreSQL credentials

set -e

AWS_REGION="us-east-1"
SECRET_NAME="smart-tutor/rds/credentials"
RDS_INSTANCE="smart-tutor-postgres"

echo "=========================================="
echo "AWS Secrets Manager Rotation Setup"
echo "=========================================="
echo ""

echo "Secret: $SECRET_NAME"
echo "RDS Instance: $RDS_INSTANCE"
echo "Region: $AWS_REGION"
echo ""

echo "Step 1: Enable Automatic Rotation"
echo "------------------------------------------"
echo ""
echo "To enable rotation, run the following command:"
echo ""
echo "aws secretsmanager rotate-secret \\"
echo "  --secret-id $SECRET_NAME \\"
echo "  --rotation-lambda-arn <ROTATION_LAMBDA_ARN> \\"
echo "  --rotation-rules '{\"AutomaticallyAfterDays\": 30}' \\"
echo "  --region $AWS_REGION"
echo ""

echo "Note: AWS Secrets Manager requires a Lambda function for rotation."
echo "The rotation Lambda must:"
echo "  1. Have permissions to access the secret"
echo "  2. Have permissions to modify RDS users"
echo "  3. Be in the same VPC as the RDS instance (if applicable)"
echo ""

echo "=========================================="
echo "Manual Rotation Alternative"
echo "=========================================="
echo ""
echo "Since automatic rotation requires additional Lambda setup,"
echo "you can manually rotate credentials periodically:"
echo ""
echo "1. Generate new password:"
echo "   NEW_PASS=\$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
echo ""
echo "2. Update RDS user password:"
echo "   psql -h smart-tutor-postgres.cmfouoe8c2p1.us-east-1.rds.amazonaws.com \\"
echo "        -U smart_tutor_admin -d smart_tutor \\"
echo "        -c \"ALTER USER smart_tutor_admin WITH PASSWORD '\$NEW_PASS';\""
echo ""
echo "3. Update secret in Secrets Manager:"
echo "   aws secretsmanager update-secret \\"
echo "     --secret-id smart-tutor/rds/credentials \\"
echo "     --secret-string '{\"username\":\"smart_tutor_admin\",\"password\":\"'\$NEW_PASS'\",\"host\":\"smart-tutor-postgres.cmfouoe8c2p1.us-east-1.rds.amazonaws.com\",\"port\":5432,\"database\":\"smart_tutor\",\"engine\":\"postgres\"}' \\"
echo "     --region us-east-1"
echo ""

echo "=========================================="
echo "Rotation Configuration Notes"
echo "=========================================="
echo ""
echo "For production deployments, consider:"
echo "  • Setting up AWS-managed rotation Lambda"
echo "  • Using rotation schedule of 30-90 days"
echo "  • Testing rotation in non-production first"
echo "  • Monitoring rotation success via CloudWatch"
echo ""
echo "Current Status: Rotation NOT enabled"
echo "Recommendation: Enable manual rotation schedule initially,"
echo "then implement automatic rotation once Lambda is configured."
echo ""
